In [1]:
import tensorflow as tf

C:\Users\Ana\Path\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Ana\Path\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Ana\Path\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Ana\Path\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a

In [12]:
#Tensor Data Types
string = tf.Variable("this is a string", tf.string)
print(string)
tf.rank(string)
number = tf.Variable(324, tf.int16)
print(number)
tf.rank(number)
floating = tf.Variable(3.567, tf.float64)
print(floating)
tf.rank(floating)
#Shape is 1 and Rank is 0 (dimensionality) because these are scalars


<tf.Variable 'Variable_5:0' shape=() dtype=int32_ref>
<tf.Variable 'Variable_6:0' shape=() dtype=float32_ref>


<tf.Tensor 'Rank_6:0' shape=() dtype=int32>

In [ ]:
#Ranks: How many dimensions
#Must be equal amount in each list
array1 = tf.Variable(["test", "Ok"], tf.string) #Rank is 1
array2 = tf.Variable([["hi, hola"], ["bye", "adios"]], tf.string) #Rank is 2
tf.rank(array1)
tf.rank(array2)

In [16]:
#Shapes: How many items in each dimension
array2.shape

NameError: name 'array2' is not defined

In [ ]:
#Changing shape
tensor1 = tf.ones([1,2,3]) #Creates a shape[1, 2, 3] and a tesnor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1]) #reshapes existing data to 2 lists, 3 inside each list, 1 element inside each of the 3
tensor3 = tf.reshape(tensor2, [3,-1])# 3 lists, 2 inside 

In [ ]:
#Types of Tensors
Variabes #Value can be changed later on
Constant #Cant be changed
Placeholder
SparseTensor

In [ ]:
#Sessions: To get vaue of tensor
with tf.Sessions() as sess:
    tensor.eval()

In [25]:
t = tf.ones([5,5,5,5])
print(t)
with tf.Session() as sess:  print(t.eval())
#t = tf.reshape(t, [125, -1]) #Means [5,5]





Tensor("ones_7:0", shape=(5, 5, 5, 5), dtype=float32)
[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1.